controller:
  allowSnippetAnnotations: true
  replicaCount: 3

  config: 
    use-forwarded-headers: true
    annotations-risk-level: Critical

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionallabels:
        release: monitoring

  priorityClassName: "priority-critical"

  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
    externalTrafficPolicy: Local

